#!/bin/bash
#
# Spawner for Bar Ain't Recursive
#
while read cmd
do
  case "$cmd" in
    volume) amixer sset Master toggle ;;
    layout) xkb-switch --next ;;
    [1-5]) bspc desktop -f ^$cmd ;;
        *) $cmd ;;
  esac
done
