library: /home/stefan/.config/beets/music.blb
directory: /mnt/usb/Backup/stefan/My_Music
import:
    move: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: albumart
plugins: bpd
pluginpath: ~/beets/myplugins
threaded: yes
color: yes

paths:
    default: $albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: Various Artists/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
